security:
    role_hierarchy:
        ROLE_CONNECT_USER: [ROLE_USER]
        ROLE_ADMIN:        [ROLE_USER, ROLE_CONNECT_USER]

    providers:
        sensiolabs_connect:
            connect_memory: ~

    firewalls:
        dev: { pattern:  "^/(_(profiler|wdt)|css|images|js)/",  security: false }
        secured_area:
            pattern:    ^/.*
            sensiolabs_connect:
                check_path: oauth_callback
                login_path: sensiolabs_connect_new_session
                failure_path: homepage
                remember_me: false
                provider: sensiolabs_connect
            logout:
                path:   /logout
                target: homepage
            anonymous: true

    access_control:
        #- { path: ^/connect-with-sensiolabs$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
